/// includes
#include "/includes.h"

#include "/Genesis.h"
#include "/genesis.lib/libraries/genesis.h"
#include "/genesis.lib/proto/genesis.h"
#include "/genesis.lib/pragmas/genesis_lib.h"

///
/// variables
struct Library *GenesisBase;
struct ParseConfig_Data pc_data;
STRPTR config;
char buffer[MAXPATHLEN];
BPTR fh;

char comment[81], login[81], password[81], phone[200], timeserver[81];
char dns1[81], dns2[81], dns3[81], domain1[81], domain2[81], domain3[81];
BOOL get_time = FALSE, save_time = FALSE;
///

/// main
int main(int argc, char *argv[])
{
   config = (argc > 1 ? argv[1] : DEFAULT_CONFIGFILE);

   if(GenesisBase = OpenLibrary(GENESISNAME, 0))
   {
      if(ParseConfig(config, &pc_data))
      {
         if(ParseNext(&pc_data))
         {
            if(strcmp(pc_data.pc_argument, "##") || strcmp(pc_data.pc_contents, "This file was generated by GENESiS Prefs"))
            {
               Printf("This is not an old genesis config file.\naborting...\n");
            }
            else
            {
               Printf("This is a valid old genesis config file.\nconverting %ls ...\n", config);
               ParseNext(&pc_data); // skip "#"

               sprintf(buffer, "%ls.new", config);
               if(fh = Open(buffer, MODE_NEWFILE))
               {
                  FPrintf(fh, "## This file was generated by genesis_converter 1.1\n##\n\n");

                  while(ParseNext(&pc_data))
                  {
                     if(!stricmp(pc_data.pc_argument, "SerialDevice"))
                     {
                        FPrintf(fh, "\nMODEM\n");
                        FPrintf(fh, "ModemID             1\n");
                        FPrintf(fh, "DropDTR             yes\n");
                        FPrintf(fh, "CommandDelay        10\n");
                        FPrintf(fh, "Answer              ATA\\r\n");
                        FPrintf(fh, "HangUp              ~~~+++~~~ATH0\\r\n");
                        FPrintf(fh, "Ring                RING\n");
                        FPrintf(fh, "Connect             CONNECT\n");
                        FPrintf(fh, "NoCarrier           NO CARRIER\n");
                        FPrintf(fh, "NoDialtone          NO DIALTONE\n");
                        FPrintf(fh, "Busy                BUSY\n");
                        FPrintf(fh, "Ok                  OK\n");
                        FPrintf(fh, "Error               ERROR\n");
                     }

                     if(!stricmp(pc_data.pc_argument, "DefaultPPP"))
                        FPrintf(fh, "UseNameserver       yes\n");


                     if(*pc_data.pc_argument == '#')
                        ; // ignore
                     else if(!stricmp(pc_data.pc_argument, "Modem"))
                        FPrintf(fh, "ModemName           %ls\n", pc_data.pc_contents);
                     else if(!stricmp(pc_data.pc_argument, "InitString"))
                        FPrintf(fh, "InitString          \"%ls\\r\"\n", pc_data.pc_contents);
                     else if(!stricmp(pc_data.pc_argument, "DialSuffix"))
                        FPrintf(fh, "DialSuffix          \"%ls\\r\"\n", pc_data.pc_contents);
                     else if(!stricmp(pc_data.pc_argument, "ShowNetwork"))
                        FPrintf(fh, "ShowInterface       %ls\n", pc_data.pc_contents);
                     else if(!stricmp(pc_data.pc_argument, "ISP"))
                     {
                        *login = *comment = *password = *phone = *timeserver = NULL;
                        get_time = save_time = FALSE;
                        *dns1 = *dns2 = *dns3 = NULL;
                        *domain1 = *domain2 = *domain3 = NULL;
                     }
                     else if(!stricmp(pc_data.pc_argument, "NameServer"))
                     {
                        if(!*dns1)
                           strncpy(dns1, pc_data.pc_contents, sizeof(dns1));
                        else if(!*dns2)
                           strncpy(dns2, pc_data.pc_contents, sizeof(dns2));
                        else if(!*dns3)
                           strncpy(dns3, pc_data.pc_contents, sizeof(dns3));
                     }
                     else if(!stricmp(pc_data.pc_argument, "DomainName"))
                     {
                        if(!*domain1)
                           strncpy(domain1, pc_data.pc_contents, sizeof(domain1));
                        else if(!*domain2)
                           strncpy(domain2, pc_data.pc_contents, sizeof(domain2));
                        else if(!*domain3)
                           strncpy(domain3, pc_data.pc_contents, sizeof(domain3));
                     }
                     else if(!stricmp(pc_data.pc_argument, "Name"))
                        strncpy(comment, pc_data.pc_contents, sizeof(comment));
                     else if(!stricmp(pc_data.pc_argument, "Organisation"))
                        ; // ignore
                     else if(!stricmp(pc_data.pc_argument, "Comment"))
                        ; // ignore
                     else if(!stricmp(pc_data.pc_argument, "AlwaysOnline"))
                        FPrintf(fh, "AutoOnline          %ls\n", pc_data.pc_contents);
                     else if(!stricmp(pc_data.pc_argument, "Login"))
                        strncpy(login, pc_data.pc_contents, sizeof(login));
                     else if(!stricmp(pc_data.pc_argument, "Password"))
                        strncpy(password, pc_data.pc_contents, sizeof(password));
                     else if(!stricmp(pc_data.pc_argument, "Phone"))
                        strncpy(phone, pc_data.pc_contents, sizeof(phone));
                     else if(!stricmp(pc_data.pc_argument, "TimeServer"))
                        strncpy(timeserver, pc_data.pc_contents, sizeof(timeserver));
                     else if(!stricmp(pc_data.pc_argument, "GetTime"))
                        get_time = TRUE;
                     else if(!stricmp(pc_data.pc_argument, "SaveTime"))
                        save_time = TRUE;
                     else if(!stricmp(pc_data.pc_argument, "INTERFACE"))
                     {
                        FPrintf(fh, "\nINTERFACE\n");
                        if(*comment)
                           FPrintf(fh, "IfComment           \"%ls\"\n", comment);
                        if(*login)
                           FPrintf(fh, "Login               \"%ls\"\n", login);
                        if(*password)
                           FPrintf(fh, "Password            \"%ls\"\n", password);
                        if(*phone)
                           FPrintf(fh, "Phone               \"%ls\"\n", phone);
                        if(*timeserver)
                           FPrintf(fh, "TimeServer          \"%ls\"\n", timeserver);
                        if(get_time)
                           FPrintf(fh, "GetTime\n");
                        if(save_time)
                           FPrintf(fh, "SaveTime\n");
                        FPrintf(fh, "UseDomainname       yes\n");
                        FPrintf(fh, "UseHostname         yes\n");
                        FPrintf(fh, "IfModemID           1\n");
                        if(*dns1)
                           FPrintf(fh, "NameServer          \"%ls\"\n", dns1);
                        if(*dns2)
                           FPrintf(fh, "NameServer          \"%ls\"\n", dns2);
                        if(*dns3)
                           FPrintf(fh, "NameServer          \"%ls\"\n", dns3);
                        if(*domain1)
                           FPrintf(fh, "DomainName          \"%ls\"\n", domain1);
                        if(*domain2)
                           FPrintf(fh, "DomainName          \"%ls\"\n", domain2);
                        if(*domain3)
                           FPrintf(fh, "DomainName          \"%ls\"\n", domain3);
                     }
                     else
                     {
                        if(*pc_data.pc_contents)
                           FPrintf(fh, "%-19ls \"%ls\"\n", pc_data.pc_argument, pc_data.pc_contents);
                        else
                           FPrintf(fh, "%ls\n", pc_data.pc_argument);
                     }
                  }
                  Close(fh);
                  sprintf(buffer, "%ls.old", config);
                  DeleteFile(buffer);
                  Rename(config, buffer);
                  sprintf(buffer, "%ls.new", config);
                  Rename(buffer, config);

                  // also convert amitcp:db/modems and append "\\r" to each init string
                  Printf("converting AmiTCP:db/modems ...\n");
                  ParseEnd(&pc_data);
                  if(ParseConfig("AmiTCP:db/modems", &pc_data))
                  {
                     if(fh = Open("AmiTCP:db/modems.new", MODE_NEWFILE))
                     {
                        while(ParseNext(&pc_data))
                        {
                           if(!stricmp(pc_data.pc_argument, "InitString"))
                           {
                              if((pc_data.pc_contents[strlen(pc_data.pc_contents) - 2] == '\\') &&
                                 (pc_data.pc_contents[strlen(pc_data.pc_contents) - 1] == 'r'))
                              FPrintf(fh, "InitString   \"%ls\"\n", pc_data.pc_contents);
                                 else
                              FPrintf(fh, "InitString   \"%ls\\r\"\n", pc_data.pc_contents);
                           }
                           else if(*pc_data.pc_argument == '#')
                              FPrintf(fh, "%ls %ls\n", pc_data.pc_argument, pc_data.pc_contents);
                           else
                           {
                              if(*pc_data.pc_contents)
                                 FPrintf(fh, "%-12ls \"%ls\"\n", pc_data.pc_argument, pc_data.pc_contents);
                              else
                                 FPrintf(fh, "%ls\n", pc_data.pc_argument);
                           }
                        }
                        Close(fh);
                        DeleteFile("AmiTCP:db/modems");
                        Rename("AmiTCP:db/modems.new", "AmiTCP:db/modems");
                     }
                     else
                        Printf("couldn't open AmiTCP:db/modems.new for output.\n");

                     // no ParseEnd() here, done later !
                  }
                  else
                     Printf("couldn't open AmiTCP:db/modems\n");
               }
               else
                  Printf("couldn't open %ls for output.\n", buffer);

               Printf("finished\n");
            }
         }
         ParseEnd(&pc_data);
      }
      CloseLibrary(GenesisBase);

   }
}

///
