#define MUISERIALNR_NETCONNECTPREFS 1
#define TAGBASE_NETCONNECTPREFS (TAG_USER | (MUISERIALNR_NETCONNECTPREFS << 16))

#define MUIA_NetConnect_Icon                    (TAGBASE_NETCONNECTPREFS | 0x1000)
#define MUIA_NetConnect_List                    (TAGBASE_NETCONNECTPREFS | 0x1001)
#define MUIA_NetConnect_Originator              (TAGBASE_NETCONNECTPREFS | 0x1002)

enum { MEN_ABOUT = 1, MEN_QUIT, MEN_RESET, MEN_LOAD, MEN_SAVE_AS, MEN_MUI , MEN_HELP };
#define DEFAULT_ACTIVE 12

